version: "3.9"

services:
  budget:
    hostname: "budget.potter.local"
    image: "potter/budget:0.1.0-SNAPSHOT"
    environment:
      - SPRING_PROFILES_ACTIVE=compose
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
  mysql:
    hostname: "mysql.potter.local"
    image: "mysql:8.0.32"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: 5s
      interval: 10s
  redis:
    hostname: "redis.potter.local"
    image: "redis:7.0.8"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: 5s
      interval: 10s
networks:
  default:
    driver: bridge
