version: "3.9"

services:
  budget:
    container_name: "budget"
    hostname: "budget.potter.local"
    image: "potter/budget:0.1.0-SNAPSHOT"
    environment:
      - SPRING_PROFILES_ACTIVE=compose
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
  mysql:
    hostname: "mysql.potter.local"
    image: "mysql:8.0.32"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
  redis:
    hostname: "redis.potter.local"
    image: "redis:7.0.8"
    ports:
      - "6379:6379"
networks:
  default:
    driver: bridge
